// ============================================================
// SPOSENCE — Base de Dados de Produtos
// ============================================================

const SPOSENCE_DATA = {
  brand: "Sposence",
  tagline: "Essências que contam histórias.",
  concentration: "27% essência pura",

  fragrance_profiles: [
    { id: "frescos",   label: "Frescos",   icon: "水", emoji: "🌊", description: "Leves e vibrantes — perfeitos para o dia a dia e o calor." },
    { id: "doces",     label: "Doces",     icon: "🍯", emoji: "🍯", description: "Gourmands aconchegantes com base de baunilha e açúcar." },
    { id: "noturnos",  label: "Noturnos",  icon: "🌙", emoji: "🌙", description: "Sedutores e marcantes para noites inesquecíveis." },
    { id: "elegantes", label: "Elegantes", icon: "✦",  emoji: "✦",  description: "Sofisticados e atemporais para ocasiões especiais." },
  ],

  // ---- PERFUMES ----
  perfumes: [
    {
      id: "light-blue",
      name: "Light Blue",
      inspired_by: "Dolce & Gabbana Light Blue",
      profile: "frescos",
      notes: { top: "Limão siciliano, maçã, cedro", heart: "Bamboo, jasmin, flor de lotus", base: "Âmbar branco, almíscar" },
      description: "Uma brisa mediterrânea em cada borrifada. Leve, cítrica e irresistível.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/light-blue-mockup.png",
      tags: ["frescos", "dia", "calor", "citrico"],
      featured: true,
    },
    {
      id: "acqua-di-gio",
      name: "Acqua di Giò",
      inspired_by: "Giorgio Armani Acqua di Giò",
      profile: "frescos",
      notes: { top: "Limão, bergamota, neroli", heart: "Jasmim, algas marinhas, rosa", base: "Cedro, musgo, almíscar branco" },
      description: "O frescor do Mediterrâneo com toque másculo e aquático.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/acqua-di-gio-mockup.png",
      tags: ["frescos", "dia", "aquatico", "masculino"],
    },
    {
      id: "mandarino",
      name: "Mandarino",
      inspired_by: "Hermès Eau de Mandarine Ambrée",
      profile: "frescos",
      notes: { top: "Mandarina, bergamota", heart: "Flor de laranjeira, gengibre", base: "Âmbar suave, sândalo" },
      description: "Vitalidade cítrica com um final quente e envolvente.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/mandarino-mockup.png",
      tags: ["frescos", "citrico", "calor"],
    },
    {
      id: "bleu-de-chanel",
      name: "Bleu de Chanel",
      inspired_by: "Chanel Bleu de Chanel",
      profile: "frescos",
      notes: { top: "Toranja, menta, pimenta rosa", heart: "Gengibre, noz-moscada, jasmim", base: "Cedro, sândalo, incenso, vetiver" },
      description: "A elegância do fresh com um coração amadeirado único.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/bleu-de-chanel-mockup.png",
      tags: ["frescos", "amadeirado", "masculino"],
      featured: true,
    },
    {
      id: "la-vie-est-belle",
      name: "La Vie Est Belle",
      inspired_by: "Lancôme La Vie Est Belle",
      profile: "doces",
      notes: { top: "Groselha preta, pêra", heart: "Íris, jasmim, flor de laranjeira", base: "Pralinê, baunilha, patchouli" },
      description: "A felicidade em forma de perfume. Doce, floral e absolutamente feminino.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      tags: ["doces", "baunilha", "gourmand", "feminino"],
      featured: true,
    },
    {
      id: "devotion",
      name: "Devotion",
      inspired_by: "Dolce & Gabbana Devotion",
      profile: "doces",
      notes: { top: "Bergamota, neroli", heart: "Flor de laranjeira absoluta, sambac", base: "Baunilha, benjoim, cedro da Virginia" },
      description: "Uma declaração floral e gourmand, quente e contemporânea.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/devotion-mockup.png",
      tags: ["doces", "floral", "baunilha"],
    },
    {
      id: "italica",
      name: "Italica",
      inspired_by: "Italica (Referência exclusiva)",
      profile: "doces",
      notes: { top: "Figos, amêndoa", heart: "Rosa turca, íris", base: "Baunilha creme, almíscar" },
      description: "Um gourmand de refinamento europeu — sensual e elegante.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/italica-mockup.png",
      tags: ["doces", "amendoa", "gourmand"],
    },
    {
      id: "baccarat-rouge",
      name: "Baccarat Rouge 540",
      inspired_by: "Maison Francis Kurkdjian Baccarat Rouge 540",
      profile: "doces",
      notes: { top: "Safranal, jasmim", heart: "Ambrofix, resina de pinheiro", base: "Cedro, fougère, âmbar" },
      description: "O perfume mais cobiçado do mundo. Uma assinatura que ninguém esquece.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/baccarat-rouge-mockup.png",
      tags: ["doces", "ambar", "premium", "unissex"],
      is_special_edition: true,
      featured: true,
    },
    {
      id: "olympea",
      name: "Olympéa",
      inspired_by: "Paco Rabanne Olympéa",
      profile: "doces",
      notes: { top: "Bergamota, cardamomo", heart: "Flor de sal, jasmim aquoso", base: "Baunilha cremosa, almíscar branco, sândalo" },
      description: "Poder e feminilidade em harmonia. Deusa moderna.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/olympea-mockup.png",
      tags: ["doces", "baunilha", "feminino"],
    },
    {
      id: "212-sexy",
      name: "212 Sexy",
      inspired_by: "Carolina Herrera 212 Sexy",
      profile: "noturnos",
      notes: { top: "Bergamota, limão, lychee", heart: "Magnólia, flor de laranjeira, gardênia", base: "Âmbar, almíscar, sândalo" },
      description: "Sedução urbana. Quente, floral e absolutamente irresistível à noite.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/212-sexy-mockup.png",
      tags: ["noturnos", "sedutor", "ambar", "feminino"],
    },
    {
      id: "libre-intense",
      name: "Libre Intense",
      inspired_by: "Yves Saint Laurent Libre Intense",
      profile: "noturnos",
      notes: { top: "Bergamota preta, lavanda fria", heart: "Flor de laranjeira marroquina, lavanda", base: "Baunilha bourbon, âmbar, almíscar" },
      description: "Liberdade e intensidade. Para a mulher que não pede permissão.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/libre-intense-mockup.png",
      tags: ["noturnos", "lavanda", "baunilha", "feminino"],
    },
    {
      id: "royal-amber",
      name: "Royal Amber",
      inspired_by: "Referência Oriental Premium",
      profile: "noturnos",
      notes: { top: "Açafrão, resina olíbano", heart: "Rosa turca, oud", base: "Âmbar real, patchouli, almíscar" },
      description: "Uma experiência oriental profunda. Majestoso e inesquecível.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/royal-amber-mockup.png",
      tags: ["noturnos", "oriental", "ambar", "oud", "unissex"],
    },
    {
      id: "tobacco-vanille",
      name: "Tobacco Vanille",
      inspired_by: "Tom Ford Tobacco Vanille",
      profile: "noturnos",
      notes: { top: "Tabaco frio, especiaria", heart: "Tabaco, baunilha, favo de mel", base: "Madeira de vetiver, cacau, baunilha seca" },
      description: "Opulento e fumê. A escolha de quem quer ser lembrado.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/tobacco-vanille-mockup.png",
      tags: ["noturnos", "amadeirado", "baunilha", "unissex"],
      featured: true,
    },
    {
      id: "one-million",
      name: "One Million",
      inspired_by: "Paco Rabanne 1 Million",
      profile: "noturnos",
      notes: { top: "Toranja, menta, canela", heart: "Rosa, especiaris", base: "Couro, patchouli, âmbar branco" },
      description: "Charisma dourado. O perfume que faz você chegar primeiro.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/one-million-mockup.png",
      tags: ["noturnos", "couro", "especiado", "masculino"],
    },
    {
      id: "invictus-victory",
      name: "Invictus Victory",
      inspired_by: "Paco Rabanne Invictus Victory",
      profile: "noturnos",
      notes: { top: "Menta gelada, tangerina", heart: "Cardamomo, guaíaco, hortelã", base: "Almíscar madeireiro, âmbar, fougère" },
      description: "Vencer tem um cheiro. Intenso, fresco e dominante.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/invictus-victory-mockup.png",
      tags: ["noturnos", "amadeirado", "menta", "masculino"],
    },
    {
      id: "libre",
      name: "Libre",
      inspired_by: "Yves Saint Laurent Libre",
      profile: "elegantes",
      notes: { top: "Lavanda francesa, tangerina", heart: "Flor de laranjeira marroquina absoluta", base: "Baunilha bourbon, cedro, almíscar" },
      description: "Liberdade feminina refinada. Um clássico moderno.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/libre-mockup.png",
      tags: ["elegantes", "lavanda", "baunilha", "feminino"],
    },
    {
      id: "libre-flowers-flames",
      name: "Libre Flowers & Flames",
      inspired_by: "YSL Libre Flowers & Flames",
      profile: "elegantes",
      notes: { top: "Framboesa, lavanda fumê", heart: "Rosa turca, flor de laranjeira", base: "Baunilha torrada, âmbar, almíscar" },
      description: "O drama de flores e o calor das chamas. Emocionante e sofisticado.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/libre-flowers-flames-mockup.png",
      tags: ["elegantes", "floral", "amadeirado", "feminino"],
    },
    {
      id: "coco-mademoiselle",
      name: "Chanel Coco Mademoiselle",
      inspired_by: "Chanel Coco Mademoiselle",
      profile: "elegantes",
      notes: { top: "Laranja, bergamota", heart: "Rosa, jasmim, ylang-ylang, mimosa", base: "Patchouli, vetiver, âmbar, baunilha, almíscar branco" },
      description: "Atemporal e magnético. A essência da feminilidade parisiense.",
      category: "perfumes",
      concentration: "27%",
      variants: [
        { size: "30ml", price: 85 },
        { size: "50ml", price: 165 },
        { size: "100ml", price: 240 },
      ],
      image: "img/coco-mademoiselle-mockup.png",
      tags: ["elegantes", "floral", "amadeirado", "feminino"],
      featured: true,
    },
  ],

  // ---- BODY SPLASHES ----
  body_splashes: [
    { id: "bs-frutado",          name: "Body Splash Frutado",          type: "Frutado",          concentration: "10%", volume: "200ml", price: 80,  description: "Explosão de frutas para o dia todo.", category: "body_splashes" },
    { id: "bs-perfumado",        name: "Body Splash Perfumado",        type: "Perfumado",        concentration: "10%", volume: "200ml", price: 90,  description: "Sofisticado e duradouro.", category: "body_splashes" },
    { id: "bs-perolado-frutado", name: "Body Splash Perolado Frutado", type: "Perolado Frutado", concentration: "10%", volume: "200ml", price: 90,  description: "Frutado com brilho sedoso na pele.", category: "body_splashes" },
    { id: "bs-perolado-perf",    name: "Body Splash Perolado Perfumado", type: "Perolado Perfumado", concentration: "10%", volume: "200ml", price: 95, description: "Perfumado com acabamento acetinado.", category: "body_splashes" },
  ],

  // ---- SKINCARE ----
  skincare: [
    { id: "sk-hidra-frutado", name: "Creme Hidratante Frutado",    type: "Creme",  price: 25, description: "Hidratação leve e perfumada com nota frutada.", category: "skincare" },
    { id: "sk-hidra-perf",    name: "Creme Hidratante Perfumado",  type: "Creme",  price: 35, description: "Pele nutrida com aroma longo e envolvente.", category: "skincare" },
    { id: "sk-baunilha",      name: "Creme Especial Baunilha",     type: "Creme",  price: 45, description: "Receita exclusiva com baunilha pura. Ultra-hidratante.", category: "skincare" },
  ],

  // ---- ACESSÓRIOS ----
  merchandise: [
    { id: "acc-ecobag",   name: "Ecobag Sposence",  price: 45, description: "Ecobag de algodão cru premium com logo Sposence.", category: "merchandise" },
    { id: "acc-chaveiro", name: "Chaveiro Sposence", price: 10, description: "Chaveiro dourado com pingente Sposence.", category: "merchandise" },
  ],

  // ---- LAYERING SUGGESTIONS ----
  layering: [
    {
      id: "layer-baunilha",
      title: "Kit Baunilha Intenso",
      description: "Combine o perfume com o creme para uma fixação que dura 2x mais.",
      perfume_ids: ["la-vie-est-belle", "devotion", "olympea"],
      skincare_ids: ["sk-baunilha"],
      splash_ids: ["bs-perfumado"],
      tag: "doces",
    },
    {
      id: "layer-citrico",
      title: "Kit Frescor Cítrico",
      description: "Camadas leves e vibrantes para o verão perfeito.",
      perfume_ids: ["light-blue", "mandarino", "acqua-di-gio"],
      skincare_ids: ["sk-hidra-frutado"],
      splash_ids: ["bs-frutado"],
      tag: "frescos",
    },
    {
      id: "layer-noturno",
      title: "Kit Noturno Premium",
      description: "Sensualidade máxima do banho ao encontro.",
      perfume_ids: ["tobacco-vanille", "royal-amber", "baccarat-rouge"],
      skincare_ids: ["sk-hidra-perf"],
      splash_ids: ["bs-perolado-perf"],
      tag: "noturnos",
    },
  ],

  // Referência ao schema técnico (para uso interno)
  technical_schema: {
    inventory_data: {
      perfumery: {
        base_ingredients: ["Essências Premium Importadas", "Base de Alta Pureza", "Fixador de Longa Duração"],
      },
    },
  },

  business: {
    packaging_note: "Todos os perfumes incluem Mini Sacola de Algodão Cru.",
    base_cost_30ml: 21.75,
    special_edition: { name: "Edição Especial 50ml", price: 200, reason: "Essência premium R$35/50ml" },
  },
};
